/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/Fk2IIkErhTD
 * Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
 */

/** Add fonts into your Next.js project:

import { Yeseva_One } from 'next/font/google'
import { Fraunces } from 'next/font/google'

yeseva_one({
  subsets: ['latin'],
  display: 'swap',
})

fraunces({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
import {
	Card,
	CardHeader,
	CardTitle,
	CardDescription,
	CardContent,
	CardFooter,
} from "@/components/ui/card";
import { Button } from "@/components/ui/button";

interface anecdotes {
	title: string;
	date: string;
	content: string;
}

export function Sage({ anecdotes }: { anecdotes: anecdotes[] }) {
	const finalAnecdotes = anecdotes
		.sort((a, b) => {
			return new Date(b.date).getTime() - new Date(a.date).getTime();
		})
		.map((anecdote) => {
			return {
				...anecdote,
				key: crypto.randomUUID(),
				// The Title field contains Markdown Asterisks and the prefix `Title: `. We remove them.
				title: anecdote.title.replaceAll(/[*#]/g, "").replace("Title: ", ""),
			};
		});

	return (
		<div className="w-full">
			<section className="w-full bg-primary py-20 px-4 sm:px-6 md:py-32 lg:px-8">
				<div className="mx-auto max-w-6xl">
					<h1 className="text-4xl font-bold tracking-[0.05em] text-primary-foreground sm:text-5xl lg:text-6xl">
						Scrum Sage
					</h1>
					<p className="mt-6 text-xl text-primary-foreground">
						Daily anecdotes about agile and scrum to inspire your team.
					</p>
				</div>
			</section>
			<div className="w-full max-w-6xl mx-auto px-4 py-8 sm:px-6 md:py-12 lg:px-8">
				<div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-2 gap-6">
					{finalAnecdotes.map((anecdote) => {
						const formattedContent = anecdote.content
							.split("\n")
							.map((line) => (
								<>
									{line}
									<br key={crypto.randomUUID()} />
								</>
							));
						return (
							<Card key={anecdote.key} className="w-full">
								<CardHeader>
									<CardTitle>{anecdote.title}</CardTitle>
									<CardDescription>{anecdote.date}</CardDescription>
								</CardHeader>
								<CardContent className="text-muted-foreground">
									<p>{formattedContent}</p>
								</CardContent>
								<CardFooter className="flex justify-end">
									<Button variant="ghost" size="icon">
										<ShareIcon className="w-4 h-4" />
										<span className="sr-only">Share</span>
									</Button>
								</CardFooter>
							</Card>
						);
					})}
					{/* <Card className="w-full">
						<CardHeader>
							<CardTitle>The Prodigal Son</CardTitle>
							<CardDescription>April 12, 2024</CardDescription>
						</CardHeader>
						<CardContent className="text-muted-foreground">
							<p>
								A man had two sons. The younger son asked his father for his
								inheritance, and the father divided his property between them.
								The younger son went away and squandered his wealth in wild
								living. When he had spent everything, a severe famine struck the
								land, and he began to be in need. He decided to return to his
								father and ask to be hired as a servant. But when he was still a
								long way off, his father saw him and was filled with compassion.
								He ran to his son, threw his arms around him and kissed him. The
								father said to his servants, "Bring the best\n robe and put it
								on him. Put a ring on his finger and sandals on\n his feet.
								Bring the fattened calf and kill it. Let's have a\n feast and
								celebrate. For this son of mine was dead and is alive\n again;
								he was lost and is found."
							</p>
						</CardContent>
						<CardFooter className="flex justify-end">
							<Button variant="ghost" size="icon">
								<ShareIcon className="w-4 h-4" />
								<span className="sr-only">Share</span>
							</Button>
						</CardFooter>
					</Card>
					<Card className="w-full">
						<CardHeader>
							<CardTitle>The Good Samaritan</CardTitle>
							<CardDescription>April 5, 2024</CardDescription>
						</CardHeader>
						<CardContent className="text-muted-foreground">
							<p>
								A man was going down from Jerusalem to Jericho, when he was
								attacked by robbers. They stripped him of his clothes, beat him
								and went away, leaving him half dead. A priest happened to be
								going down the same road, and when he saw the man, he passed by
								on the other side. So too, a Levite, when he came to the place
								and saw him, passed by on the other side. But a Samaritan, as he
								traveled, came where the man was; and when he saw him, he took
								pity on him. He went to him and bandaged his wounds, pouring on
								oil and wine. Then he put the man on his own donkey, brought him
								to an inn and took care of him. The next day he took out two
								denarii and gave them to the innkeeper. "Look\n after him," he
								said, "and when I return, I will reimburse you\n for any extra
								expense you may have."
							</p>
						</CardContent>
						<CardFooter className="flex justify-end">
							<Button variant="ghost" size="icon">
								<ShareIcon className="w-4 h-4" />
								<span className="sr-only">Share</span>
							</Button>
						</CardFooter>
					</Card>
					<Card className="w-full">
						<CardHeader>
							<CardTitle>The Mustard Seed</CardTitle>
							<CardDescription>March 29, 2024</CardDescription>
						</CardHeader>
						<CardContent className="text-muted-foreground">
							<p>
								Jesus told them another parable: "The kingdom of heaven is
								like\n a mustard seed, which a man took and planted in his
								field.\n Though it is the smallest of all seeds, yet when it
								grows, it\n is the largest of garden plants and becomes a tree,
								so that the\n birds come and perch in its branches."
							</p>
						</CardContent>
						<CardFooter className="flex justify-end">
							<Button variant="ghost" size="icon">
								<ShareIcon className="w-4 h-4" />
								<span className="sr-only">Share</span>
							</Button>
						</CardFooter>
					</Card> */}
				</div>
			</div>
		</div>
	);
}

function ShareIcon(props) {
	return (
		<svg
			{...props}
			xmlns="http://www.w3.org/2000/svg"
			width="24"
			height="24"
			viewBox="0 0 24 24"
			fill="none"
			stroke="currentColor"
			strokeWidth="2"
			strokeLinecap="round"
			strokeLinejoin="round"
		>
			<path d="M4 12v8a2 2 0 0 0 2 2h12a2 2 0 0 0 2-2v-8" />
			<polyline points="16 6 12 2 8 6" />
			<line x1="12" x2="12" y1="2" y2="15" />
		</svg>
	);
}

function XIcon(props) {
	return (
		<svg
			{...props}
			xmlns="http://www.w3.org/2000/svg"
			width="24"
			height="24"
			viewBox="0 0 24 24"
			fill="none"
			stroke="currentColor"
			strokeWidth="2"
			strokeLinecap="round"
			strokeLinejoin="round"
		>
			<path d="M18 6 6 18" />
			<path d="m6 6 12 12" />
		</svg>
	);
}
